### ISSUE TITLE
Error ! Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by raghavSrih** [hiteshjoshi/node-stanford-corenlp#10]
Hi,

Can you list the steps I should follow to resolve this error 

Could not create class edu.stanford.nlp.pipeline.StanfordCoreNLP java.lang.UnsupportedClassVersionError: edu/stanford/nlp/pipeline/StanfordCoreNLP : Unsupported major.minor version 52.0

Regards,
Raghav

**Comment by hiteshjoshi** [comment]
thats when you use old java version.!
