### ISSUE TITLE
Other language than english

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [hiteshjoshi/node-stanford-corenlp#14]
Hello,

How can I use another language than English to process my text ?

Thank you,

Guillaume Leclerc

**Comment by yourcontainer** [comment]
ofcource, visit http://stanfordnlp.github.io/CoreNLP/
follow Human languages supported section, and download jar module what do you need

**Comment by GuillaumeLeclerc** [comment]
I know this but how do I select the language ?

**Comment by hiteshjoshi** [comment]
Like this https://github.com/iwater/node-stanford-corenlp/commit/c067186a68eab7687c46f5a7956226c34e524689

**Comment by hiteshjoshi** [comment]
Added support for language, https://github.com/hiteshjoshi/node-stanford-corenlp#async-mode
