### ISSUE TITLE
Support for CoreNLP-3.6

### ISSUE THREAD

**Issue by Illizian** [hiteshjoshi/node-stanford-corenlp#16]
Hi, thanks for the library.

I require the latest core (3.6.0) to make use of the OpenIE annotator. It seems your library works perfectly with the latest core with one change to the [`loadLibrary()`](https://github.com/hiteshjoshi/node-stanford-corenlp/blob/e36ad617539a1cccf85f15884d5f8cbb80d71eee/lib/StanfordNLP.js#L12-L19) method as it now makes use of [SLF4J](http://www.slf4j.org/) library.

``` js
function loadLibrary(path,version){
    java.classpath.push(path+"/slf4j-api.jar");
    java.classpath.push(path+"/slf4j-simple.jar");
    // [...]
}
```

Correct me if I'm wrong but it doesn't appear to cause issues adding incorrect classpaths (as I discovered when I typod `slf4j`) so it doesn't seem like a version check is required?

Happy to make a PR if you can advise on how to handle this with 'backward compatibility'.

**Comment by hiteshjoshi** [comment]
Send a pull request.

**Comment by Illizian** [comment]
Thanks @hiteshjoshi - PR #19 is in
