### ISSUE TITLE
How should this all be installed?

### ISSUE THREAD

**Issue by person666** [hiteshjoshi/node-stanford-corenlp#18]
[This is a link to the issues I am having installing this package](http://stackoverflow.com/questions/36273714/error-could-not-create-class-edu-stanford-nlp-pipeline-stanfordcorenlp-how-to)

**Comment by hiteshjoshi** [comment]
https://github.com/hiteshjoshi/node-stanford-corenlp/issues/8
The sync function has got bugs it in. Didnt get time to fix. I will look into this coming weekend.
