### ISSUE TITLE
Why does the Async mode example return "[Error: Load a pipeline first.] undefined"

### ISSUE THREAD

**Issue by person666** [hiteshjoshi/node-stanford-corenlp#20]
The [Async mode example](https://github.com/hiteshjoshi/node-stanford-corenlp#async-mode) returns `[Error: Load a pipeline first.] undefined` with everything set up as it should be. How can I get it working?

**Comment by hiteshjoshi** [comment]
https://github.com/hiteshjoshi/node-stanford-corenlp/issues/8#issuecomment-132071560

**Comment by person666** [comment]
```
var NLP = require('stanford-corenlp');

var coreNLP = new NLP.StanfordNLP({

    "nlpPath":"./corenlp",
    "version":"3.6.0"

},function(err) {
  coreNLP.process('This is so good.', function(err, result) {
    console.log(err,JSON.stringify(result));
  });
});
```

after updating to latest commit
returns 

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at getProperties (/home/user/code/stanford-corenlp-test/node_modules/stanford-corenlp/lib/util.js:4:13)
    at Object.exports.setProperties (/home/user/code/stanford-corenlp-test/node_modules/stanford-corenlp/lib/util.js:16:3)
    at /home/user/code/stanford-corenlp-test/node_modules/stanford-corenlp/lib/StanfordNLP.js:77:16
```

**Comment by hiteshjoshi** [comment]
try now

**Comment by person666** [comment]
I ran `npm install https://github.com/hiteshjoshi/node-stanford-corenlp.git` then tried again still getting the error. I also tried reinstalling java the npm package.

**Comment by qrpike** [comment]
I too am getting the same error. Any advice?

**Comment by Ricsie** [comment]
I have the same error on Async example code. How can I solve it? I'm Really stuck there...

**Comment by rneha725** [comment]
I am stuck with the same code!!

**Comment by hiteshjoshi** [comment]
https://github.com/hiteshjoshi/node-stanford-corenlp/issues/8#issuecomment-132071560

**Comment by Ricsie** [comment]
the problem is we all are using the async mode. even the original quetion states async mode is problematic. why are you keep linking us to the comment "use async mode"? if the async mode doesnt work?

**Comment by hiteshjoshi** [comment]
my bad... can any of you tell, which version of core NLP are you using?

**Comment by Ricsie** [comment]
thank you for your fast response. Im using stanford-corenlp-full-2015-12-09.zip
