### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jczaplew** [hiteshjoshi/node-stanford-corenlp#5]
Following the instructions in the README, every time I try to initialize a new processor (`new NLP.StanfordNLP(...`) the script bails with this error:

```
Invalid memory access of location 0x0 rip=0x1091974c6
Segmentation fault: 11
```

My environment:
Node -- 0.12.6 
OS -- OS X 10.10.3
Java -- 1.8.0_45
Stanford CoreNLP -- 3.5.2 (2015-04-20)

Any and all advice would be appreciated. Thank you!

**Comment by hiteshjoshi** [comment]
This doenst really sounds like an error of this package. Can you try npm -v and tell me what you get.

**Comment by jczaplew** [comment]
2.11.3
